![Práctica 4- Librería NUMPY](img/cabecera-Numpy.png)

# Numpy.

`Numpy` es un paquete de cálculo científico para Python. Es el más utilizado en Python para cálculo numérico. Entre las características mas destacadas están:

- Vectores, matrices y estructuras N-dimensionales muy versatiles y poderosos.
- Sofisticadas funciones de broadcasting.
- Utilidades de algebra lineal, transformada de Fourier y capacidades para números aleatorios.

La librería está implementada en C y Fortran, por lo que el rendimiento en el cálculo con vectores es muy alto.

La documentación sobre la librería la puedes encontrar en: <a>http://www.numpy.org/</a>

Para empezar a trabajar con esta librería debemos importarla. Lo mas común es importarla utilizando el alias `np`:

In [2]:
import numpy as np

## Creando arrays con `Numpy`.

En el paquete `Numpy` el término `array` se utilizada para definir vectores, matrices o cualquier estructura n-dimensional.

Hay varias formas de inicializar un array en Numpy, como por ejemplo:
- Utilizando listas o tuplas de Python.
- Con funciones dedicadas a generar arrays.

### Desde listas o tuplas.

Podemos crear un vector de una dimensión con la funcion `array`:

In [ ]:
v = np.array([1,2,3,4])
v

O crear un vector de dos dimensiones usando una lista de listas.

In [ ]:
M = np.array([[1,2],[3,4]])
M

Ambas estructuras tienen el mismo tipo con distintas dimensiones

In [ ]:
print(type(v))
print(v.shape)
print(type(M))
print(M.shape)

Como podemos ver, los arrays en Numpy se denominan `numpy.ndarray`.

Para conocer el número de elementos de un array (independientemente de sus dimensiones) utilizamos la propiedad `size`:

In [ ]:
print('Elementos en el vector: ', v.size)
print('Elementos en la matriz: ', M.size)

Aunque los array de Numpy tienen un gran parecido con las listas de Python, existen varias diferencias importantes. Por ejemplo, las listas de Python son heterogéneas, es decir, pueden contener cualquier tipo de objeto. Sin embargo, los arrays de Numpy son homogéneos, es decir, el tipo de elementos que almacena se define al crearlo.

Utilizando la propiedad `dtype` podemos conocer el tipo de dato que almacena el array:

In [ ]:
M.dtype

Si intentamos asignar un tipo incorrecto (o que no pueda convertirse) nos dará un error:

In [ ]:
M[0,0]='Hola'

Si queremos que un array sea de un tipo dado, podemos indicarlo en su inicialización utilizando el argumento `dtype`:

In [ ]:
np.array([[1, 2], [3, 4]], dtype=complex)

Los tipos más comunes son: `int`, `float`, `complex`, `bool`, `object`, etc.

También podemos indicar el tamaño en bits de algunos de estos tipos, como por ejemplo: `int64`, `int16`, `float128`, `complex128`.

### Funciones para  crear arrays.

Numpy dispone de una gran cantidad de funciones para crear arrays de gran tamaño y de distinto tipo de forma automática. A continuación vamos a ver algunos de ellos.


#### arange 

Para crear un array de valores desde un inicio hasta un fin con un salto dado (como los bucles `for`):

In [ ]:
# argumentos: inicio, fin, salto
np.arange(0, 11, 2)

#### linspace

Para crear un array de valores equidistantes, incluyendo en el array el valor inicial y final:

In [ ]:
# argumentos: primero, último, numero de valores
np.linspace(0, 13, 6)

#### logspace

Crea un vector con números exponenciales cuya base es común y los exponentes están equidistantes: 

In [ ]:
np.logspace(0, 10, 10, base=np.e)

Los valores obtenidos son: $e^0$, $e^1$, ..., $e^{10}$

#### zeros, ones

Se pueden crear vectores inicializados todos los elementos a 0:

In [ ]:
np.zeros(4)

O inicializados todos a 1:

In [ ]:
np.ones(5)

Si queremos indicar un array con distintas dimensiones, estas se pueden pasar como una tupla:

In [ ]:
np.zeros( (2,3) )

Si queremos inicializar con cualquier otro valor, podemos realizar una operación aritmética:

In [ ]:
np.ones(6)*5

#### eye
Para crear un array de 2 dimensiones con valores de 1 en la diagonal:

In [ ]:
np.eye(5)

#### Números aleatorios

También se pueden crear arrays aleatorios con diversas funciones:

In [ ]:
np.random.rand(5,5)

O valores aleatorios siguiendo una distribución normal:

In [ ]:
np.random.randn(5,5)

Puedes ver las distintas funciones de números aleatorios utilizando la orden `help`:

In [ ]:
help(np.random)

La orden `help` se utiliza para conocer información de cualquier objeto, método o propiedad. Si queremos conocer los parámetros de cualquier función de números aleatorios podemos pedir ayuda:

In [ ]:
help(np.random.randint)

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 1**: Lee la información proporcionada por la orden `help` anterior y prueba a generar una matriz de 4x5 de números enteros aleatorios.


In [ ]:
#programar aquí la solución:
np.random.randint(5, size=(4,5))

## Otras propiedades de los arrays

Los arrays de Numpy tienen otras propiedades interesantes:

In [ ]:
#Tamaño en bytes de un elemento del array
M.itemsize

In [ ]:
#Tamaño completo del array en bytes
M.nbytes

In [ ]:
#Número de dimensiones del array
M.ndim

In [ ]:
#Transpuesta
M.T

## Acceso y manipulación de arrays

### Uso simple de los índices

Podemos acceder a los elementos de un array usando corchetes e índices separados por comas. Como en las listas, los array de Numpy también **empiezan en 0**.

In [ ]:
v[0]

In [ ]:
M[1,1]

Si en una matriz sólo utilizamos un índice, Python devuelve la fila completa:

In [ ]:
M[1]

Por esta razón, también se pueden acceder a los arrays multidimensionales de Numpy como si fueran listas de listas:

In [ ]:
M[1][0]

Para asignar nuevos valores a un array, se hace como una variable cualquiera:

In [ ]:
M[0,0] = 7
M

También se pueden acceder o asignar valores en una dimensión completa. Para ello utilizamos el caracter *dos puntos* (`:`) en las dimensiones que queremos manipular por completo.

In [ ]:
#Acceder a una fila completa
M[1,:]

In [ ]:
#Acceder a una columna completa
M[:,0]

In [ ]:
#Asignar el valor 0 a toda una fila
M[0,:] = 0
M

### Acceso por trozos (*index slicing*)

El uso de los dos puntos para acceder a subarrays dentro de un array de Numpy se conoce como *index slicing* o acceso por trozos. Esta técnica nos permite manipular una parte del array y su sintaxis mas habitual es:
```python
Vector[inicio:fin:salto]
```

In [ ]:
A = np.array([1,3,5,7,9])
A[1:3]

Los *trozos* de arrays pueden modificarse como cualquier otro array, modificando de esta forma el array completo.

In [ ]:
A[1:3]=[-2,-3]
A

Se puede omitir cualquiera de los 3 parámetros:

In [ ]:
A[::]

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 2**: Prueba a obtener subarrays indicando sólo uno de los tres parámetros y observa lo que se obtiene.


In [ ]:
A = np.array([1,3,5,7,9,11,13,15,17,19])
#Los 3 primeros elementos
print(A[:3])
#Desde el 4 elemento
print(A[4:])
#Los elementos pares
print(A[::2])

Si se utilizan **índices negativos** estos empiezan a contar desde el final del array.

In [ ]:
#El último elemento
A[-1]

In [ ]:
#Los 3 últimos elementos
A[-3:]

El acceso por *trozos* funciona exactamente igual en arrays de varias dimensiones:

In [ ]:
A = np.array([
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]
     ])
A

In [ ]:
#Una submatriz de la original
A[1:4, 1:4]

In [ ]:
#Los elementos en filas y columnas pares
A[::2, ::2]

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 3**: Prueba a obtener la submatriz de 3x3 de la esquina inferior derecha de la matriz A.


In [ ]:
#Submatriz 3x3 de la esquina inferior derecha
A = np.array([
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]
     ])

A[-3:, -3:]

### Usar listas de índices (*fancy indexing*)

Otra forma de obtener un subarray es utilizando una lista para indicar a que índices en concreto se quiere acceder.

In [ ]:
#Obtener las filas 1, 2, y 3 de la matriz A
filas = [1, 2, 3]
A[filas]

In [ ]:
#Obtener 3 elementos en concreto de la matriz A
columnas = [1, 2, -1] 
A[filas,columnas]

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 4**: Prueba a indicar 4 índices en la lista de columnas. ¿Se puede?.


In [ ]:
A = np.array([
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]
     ])

columnas = [1, 2, 3, 4]
filas = [1, 2, 3]

A[filas, columnas]

# No, no se puede ya que el número de filas y columnas no coincide. Al especificar filas y columnas, estamos seleccionando elementos específicos de la matriz, por tanto si seleccionamos 3 filas y 4 columanas, habra una columna que no se corresponde con ninguna fila, por lo que no se puede realizar la operación.

Tambien podemos indicar los índices como si se tratara de una máscara. Para ello debemos utilizar un array de Numpy con valores de tipo `bool`, donde los elementos que queremos seleccionar valdrán `True` y los que no valdrán `False`.

In [ ]:
B = np.array([0, 1, 2, 3, 4])
print(B)
row_mask = np.array([True, False, True, False, False])
B[row_mask]

Esta característica es muy útil para seleccionar elementos de un array que cumplan ciertas condiciones. Para ello creamos la máscara utilizando operadores de comparación.

In [ ]:
#Creamos un vector de reales
x = np.arange(0, 10, 0.5)
x

In [ ]:
#Creamos una máscara comparando todos los elementos de x con nuestros valoes umbrales
mask = (5 < x) * (x < 7.5) # El producto es AND y la suma es OR
mask

In [ ]:
#Operamos sobre los que cumplen la máscara.
x[mask] = 3
x

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 5**: Crea una matriz aleatoria de números enteros entre 0 y 10, y después selecciona los elementos iguales a 5.


In [ ]:
#Crear matriz aleatoria
n = np.random.randint(10, size=(10,10))
#Crear máscara para elementos iguales a 5
mask = (n==5)
#Aplicar máscara
n[mask]

Si queremos convertir una máscara en un array de índices, podemos utilizar la función **`where`**. Esta función es útil para saber en que posiciones están los elementos que cumplen cierta condición.

In [ ]:
x = np.arange(0, 10, 0.6)
print('Valores: ', x)
mascara = (x>8)
print('Máscara: ', mascara)
indices = np.where(mascara)
indices

## Álgebra lineal

Numpy nos permite realizar operaciones de álgebra lineal con sus vectores, de forma eficiente.

### Operaciones escalares

Podemos utilizar los típicos operadores de suma, resta, multiplicación y división con arrays y números escalares.

In [ ]:
v1 = np.arange(0, 5)
#Sumar un numero a todos los elementos de un vector
v1 + 2

In [ ]:
#Multiplicar un número a todos los elementos de un vector
v1 * 2

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 6**: Prueba a sumar y multiplicar un número a una matriz.


In [3]:
A = np.array([[1, 2], [3, 4]])
print("Suma (A + 10):\n", A + 10)
print("Multiplicación (A * 5):\n", A * 5)


Suma (A + 10):
 [[11 12]
 [13 14]]
Multiplicación (A * 5):
 [[ 5 10]
 [15 20]]


<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 7**: Prueba a dividir una matriz por un número y un número por una matriz.


In [4]:
# Dividir una matriz por un número
print("Matriz / número:\n", A / 2)

# Dividir un número por una matriz (elemento a elemento)
print("Número / matriz:\n", 10 / A)

Matriz / número:
 [[0.5 1. ]
 [1.5 2. ]]
Número / matriz:
 [[10.          5.        ]
 [ 3.33333333  2.5       ]]


### Operaciones entre arrays elemento a elemento.

Cuando sumamos, restamos, multiplicamos y dividimos arrays entre ellos, la operación por defecto se realiza elemento a elemento.

In [ ]:
#Multiplicar matrices elemento a elemento
print(A)
A * A

In [ ]:
#Multiplicar vectores elemento a elemento.
print(v1)
v1 * v1

Si multiplicamos arrays con dimensiones compatibles, obtenemos multiplicaciones elemento a elemento en cada fila.

In [ ]:
print(A.shape)
print(v1.shape)

In [ ]:
print(A)
print(v1)
A * v1

### Operaciones entre matrices

Para multiplicar matrices tenemos dos opciones. La primera es utilizar la función `dot` cuyos operadores pueden ser matriz-matriz, matriz-vector o vector-vector.

In [ ]:
np.dot(v1, v1)

In [ ]:
np.dot(A, v1)

In [ ]:
np.dot(A,A)

La segunda opción consiste en utilizar el objeto `matrix`. Este objeto nos permite realizar operaciones matriciales con los típicos operadores de suma, resta, multiplicación, etc.

In [ ]:
#Convertir los arrays en matrices
M = np.matrix(A)
v = np.matrix(v1).T #vector columna
v

In [ ]:
#Producto entre matrices.
M * M

In [ ]:
#Producto entre vectores
v.T * v

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 8**: Prueba a realizar distintos tipos de productos, sumas y restas entre vectores y matrices.


In [5]:
B = np.array([[5, 6], [7, 8]])
v = np.array([1, 2])

print("Suma de matrices:\n", A + B)
print("Resta de matrices:\n", A - B)
print("Producto punto (Matriz-Vector):\n", np.dot(A, v))
print("Producto matricial (A x B):\n", np.dot(A, B))

Suma de matrices:
 [[ 6  8]
 [10 12]]
Resta de matrices:
 [[-4 -4]
 [-4 -4]]
Producto punto (Matriz-Vector):
 [ 5 11]
Producto matricial (A x B):
 [[19 22]
 [43 50]]


### Transformación de matrices y arrays.

Además de la transformada (`.T`), existen otras transformaciones que se pueden realizar sobre los objetos matriz.

Creemos la siguiente matriz de números complejos:

In [ ]:
C = np.matrix([[1j, 2j], [3j, 4j]])
C

Se pueden obtener diferentes transformaciones:

In [ ]:
#conjugada
np.conjugate(C)

In [ ]:
#conjugada transpuesta
C.H

In [ ]:
#inversa = np.inv(C)
C.I

In [ ]:
#parte real = np.real(C)
C.real

In [ ]:
#parte imaginaria = np.imag(C)
C.imag

In [ ]:
#valor absoluto
np.abs(C)

In [ ]:
#determinante
print(C)
np.linalg.det(C)

## Cálculos estadísticos

Los arrays de Numpy son útiles para almacenar conjuntos de datos y realizar cálculos estadísticos con ellos.

In [ ]:
A=np.random.randint(0,100,(3,4))
print(A)

#Media de la columna 3 de la matriz
np.mean(A[:,3])

In [ ]:
#Desviación estándar
np.std(A[:,3])

In [ ]:
#Varianza
np.var(A[2,:])

In [ ]:
#Mínimo y máximo
A.min(), A.max()

In [ ]:
#Suma y producto
d = np.arange(1, 10)
np.sum(d), np.prod(d)

In [ ]:
#Suma acumulativa
np.cumsum(d)

In [ ]:
#Producto acumulativo
np.cumprod(d)

In [ ]:
#Suma de la diagonal
np.trace(A)

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 9**: ¿Existe alguna otra forma de calcular la suma de la diagonal sin utilizar `trace`?


In [8]:
suma_diagonal = np.sum(np.diag(A))
print("Suma diagonal (sin trace):", suma_diagonal)
# Segunda Forma
print("Suma diagonal (índices):", A[np.arange(A.shape[0]), np.arange(A.shape[0])].sum())

Suma diagonal (sin trace): 5
Suma diagonal (índices): 5


Algunas funciones, como el máximo, el mínimo o la media, permiten realizar operaciones en un eje en concreto, con el parámetro `axis`. Por ejemplo se puede calcular el máximo por filas o por columnas, obteniendo varios valores:

In [ ]:
A

In [ ]:
print("Máximos de cada col.: ", A.max(axis=0))
print("Máximos de cada fila: ", A.max(axis=1))

## Jugando con las dimensiones de un array

Las dimensiones de un array de Numpy pueden ser cambiadas sin volver a copiar los datos que contiene, lo cual hace que dicha operación sea muy rápida para arrays muy grandes.

In [ ]:
A=np.random.randint(0,100,(3,4))
A

In [ ]:
n, m = A.shape
print(n, 'filas y', m, 'columnas')

In [ ]:
B = A.reshape((1,n*m))
B

In [ ]:
#Modificamos el nuevo array
B[0,0:7] = 5
B

In [ ]:
#Comprobamos que ha cambiado el original
A 

Podemos utilizar la función `flatten` para convertir un array de varias dimensiones en un vector. Pero esta función crea una copia de los datos.

In [ ]:
B = A.flatten()
B

In [ ]:
B[0:4] = 10
B

In [ ]:
#Comprobamos si A ha cambiado
A

## Añadiendo una nueva dimensión (BORRAR)

Con `newaxis` podemos insertar una nueva dimensión en un array, por ejemplo, convirtiendo un vector en una matriz de una fila o una columna:

In [ ]:
v = np.array([1,2,3])
np.shape(v)

In [ ]:
#Crear una matriz columna con v
v[:, np.newaxis]

In [ ]:
#Dimensiones de la matriz columna
v[:,np.newaxis].shape

In [ ]:
#Dimensiones de la matriz fila
v[np.newaxis,:].shape

## Uniendo y repitiendo vectores

Las funciones `repeat`, `tile`, `vstack`, `hstack`, y `concatenate` pueden crear grandes arrays a partir de otros más pequeños:

### tile and repeat

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)
#Repetir cada elemento 3 veces
np.repeat(a, 3)

<img src="img/ejercicio2.png" style="float: left">

**Ejercicio 10**: ¿Se puede repetir un array de 2 dimensiones por filas o por columnas? (busca en la ayuda)


In [9]:
a = np.array([[1, 2], [3, 4]])
print("Repetir filas:\n", np.repeat(a, 2, axis=0))
print("Repetir columnas:\n", np.repeat(a, 2, axis=1))

Repetir filas:
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
Repetir columnas:
 [[1 1 2 2]
 [3 3 4 4]]


Se puede repetir la matriz completa en lugar de sus elementos:

In [ ]:
np.tile(a, 3)

### concatenate
Tambien se pueden unir 2 arrays distintos (si sus dimensiones lo permiten):

In [ ]:
b = np.array([[5, 6]])
print(b)
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b.T), axis=1)

## Asignar arrays: copia y "copia profunda".

Para mejorar el rendimiento, las asignaciones en Python normalmente no realizan copias completas de los objetos. Esto es importante, por ejemplo, cuando los objetos se pasan entre funciones, para evitar excesivas operaciones de copia de grandes cantidades de memoria. Técnicamente esto se llama *paso por referencia*.

Con los arrays de Numpy, pasa exactamente lo mismo. Veamos unos ejemplos.

In [ ]:
#Creamos un array
A = np.array([[1, 2], [3, 4]])
A

In [ ]:
#Creamos un nuevo array B que hace referencia a A
B = A 

In [ ]:
#Los cambios en B afectan a A
B[0,0] = 10
print('Array B:\n',B)
print('Array A:\n',A)

Si queremos hacer una copia independiente, entonces necesitamos realizar una *"copia profunda"* utilizando la función  `copy`:

In [ ]:
C = np.copy(A)
C[0,0] = -3
print('Array C:\n',C)
print('Array A:\n',A)

Para conocer si dos array son el mismo (uno es referencia de otro) se puede utilizar el operador `is`:

In [ ]:
if A is B:
    print('A y B son el mismo array.')
if A is C:
    print('A y C son el mismo array.')

## Iterando sobre los elementos del array

Aunque realizar operaciones elemento a elemento con un array es mas lento que las operaciones entre vectores, a veces es necesario iterar sobre los elementos de un array. La manera mas conveniente de realizarlo es utilizando el bucle `for`:

In [ ]:
v = np.array([1,2,3,4])

for element in v:
    print(element)

In [ ]:
M = np.array([[1,2], [3,4]])

for row in M:
    print("Fila", row)
    
    for element in row:
        print(element)

Cuando necesitamos iterar sobre cada elemento y modificarlo, es conveniento utilizar la funcion `enumerate`, que nos devuelve el elemento y el índice: 

In [ ]:
print(M)
for x, row in enumerate(M):
    print("x =", x, ", row =", row)
    
    for y, element in enumerate(row):
        print("  y =", y, ", valor =", element)
       
        #Elevar cada elemento al cuadrado
        M[x,y] = element ** 2

In [ ]:
#Cada elemento está ahora al cuadrado
M

Los *notebooks* de *Jupyter* disponen de **palabras mágicas** que nos permiten realizar acciones especiales. Entre ellas está la orden `%%timeit` que ejecuta un código miles de veces y calcula el tiempo medio de ejecución de dicho código.

Vamos a utilizar la palabra mágica `%%timeit` para comprobar que código es mas rápido: el iterativo o el vectorial.

In [ ]:
%%timeit
#Aproximación iterativa
M1 = np.array([[1,2], [3,4]])
for x, row in enumerate(M1):
    for y, element in enumerate(row):
        M1[x, y] = element ** 2

In [ ]:
%%timeit
#Aproximación vectorial
M2 = np.array([[1,2], [3,4]])
np.power(M2,2,out=M2)

In [ ]:
%%timeit
#Aproximación mixta
M3 = np.array([[1,2], [3,4]])
for index, element in np.ndenumerate(M3):
    M3[index] = element ** 2

## Utilizando arrays en una condición

Cuando utilizamos arrays en ordenes `if` o expresiones lógicas, necesitamos obtener un único valor lógico. Para ello podemos utilizar los métodos `any` o `all`.

In [ ]:
M

In [ ]:
#"any" equivale a un OR lógico entre todos los elementos del vector
if (M > 5).any():
    print("Al menos un elemento de M es mayor que 5")
else:
    print("Ningún elemento es mayor que 5")

In [ ]:
#"all" equivale a un AND lógico entre todos los elementos del vector
if (M > 5).all():
    print("TODOS los elementos de M son mayores que 5")
else:
    print("Algún elemento en M no es mayor que 5")

## Referencias para ampliar.

* https://numpy.org/
* https://numpy.org/doc/stable/
* https://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial.html
* https://numpy.org/doc/stable/