![Práctica 2 - Librería NUMPY](img/cabecera-Numpy.png)

# Ejercicios de Numpy

#### 1. Importa el paquete numpy con el nombre `np`.

In [2]:
import numpy as np

#### 2. Crea un vector de tamaño 10 lleno de ceros.

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Crea un vector de ceros de tamaño 10 pero donde el quinto valor sea 1.

In [8]:
n=np.zeros(10)
n[4]=1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Crea un vector con todos los enteros del 10 al 49.

In [12]:
np.arange(10,49,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5.  Dale la vuelta a un vector (el primer elemento debe ser el último).

In [25]:
print(n)
np.flip(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 6. Encuentra los índices de todos los valores distintos de cero el vector \[1,2,0,0,4,0\].

In [23]:
m=np.array([1,2,0,0,4,0])
mask=(m!=0)
np.where(mask)

(array([0, 1, 4]),)

#### 7. Crea una matriz identidad de 3x3 (matriz de ceros con la diagonal principal a 1).

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Crea un array de 3x3x3 de valores aleatorios.

In [26]:
np.random.rand(3,3,3)

array([[[0.10307527, 0.35565055, 0.58644419],
        [0.19577216, 0.69911286, 0.84275829],
        [0.38386186, 0.32841798, 0.1012401 ]],

       [[0.2465442 , 0.45093011, 0.24843797],
        [0.72734483, 0.6212026 , 0.80544495],
        [0.79873232, 0.59324117, 0.63319119]],

       [[0.27690562, 0.01247624, 0.67340143],
        [0.53495182, 0.37109029, 0.86431701],
        [0.88652123, 0.00110024, 0.0810548 ]]])

#### 10. Crea una matriz de 10x10 con números aleatorios y encuentra el mínimo y el máximo.

In [30]:
n=np.random.rand(10,10)
min=np.min(n)
max=np.max(n)
print("Valor mínimo: ", min)
print("Valor máximo: ", max)

Valor mínimo:  0.007484961532430168
Valor máximo:  0.9720162836589075


#### 11. Crea un vector aleatorio de tamaño 30 y calcula la media.

In [31]:
n=np.random.rand(30)
mean=np.mean(n)
print("Media: ", mean)

Media:  0.5466023618869161


#### 12. Crea un array de 2 dimensiones relleno de ceros y con el valor 1 en los bordes.

In [ ]:
n=np.zeros((10,10))
n[0,:]=1
n[:,0]=1
n[-1,:]=1
n[:,-1]=1
print(n)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 13. Crea una matriz de 8x8 rellena con un patrón de tablero de ajedrez (utiliza 0 y 1).

In [ ]:
n = np.zeros((8,8))
n[1::2, ::2] = 1
n[::2, 1::2] = 1
print(n)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 14. Normaliza una matriz aleatoria de 5x5 para que sus valores estén entre 0 y 1 (ambos deben estar incluidos).

In [54]:
np.random.rand(5,5)
min=np.min(n)
max=np.max(n)
n=(n-min)/(max-min)
print(n)

[[0.44095312 0.56519538 0.44896709 0.65784961 0.68436917]
 [1.         0.30899066 0.         0.25814604 0.17767962]
 [0.28275861 0.46034142 0.38153886 0.2386929  0.63293197]
 [0.51957086 0.36669824 0.82001715 0.9736881  0.2566869 ]
 [0.52401046 0.45021849 0.86335906 0.11820864 0.32841273]]


#### 15. Multiplica una matriz de 5x3 por una de 3x2.

#### 16. Dado un array de 1 dimensión, cambia el signo de los elementos cuyo valor esté entre 3 y 8.

#### 17. Encontrar los valores comunes en dos arrays.
SUGERENCIA: En Numpy hay funciones para manipular los arrays como conjuntos (intersección, unión, diferencia, ...)

#### 18. ¿Es la siguiente expresión cierta?

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 19. Encuentra 3 formas diferentes de extraer la parte entera de los valores de un array de números reales aleatorios.

#### 20. Crea una matriz de 5x5 en la que todas las filas contengan el rango de 0 a 4.

#### 21. Crea un vector con 10 valores desde el 0 hasta el 1, pero sin incluir ni el 0, ni el 1.

#### 22. Crea un vector aleatorio de tamaño 10 y ordénalo.

#### 23. Considera dos arrays de enteros aleatorios A y B de tamaño 3. Muéstralos y comprueba si son iguales.

#### 24. Crea un array aleatorio de tamaño 10 y cambia el máximo valor por 0.

#### 25. Encontrar en un array de números reales el valor mas cercano a un número dado que el programa debe pedir por teclado.

#### 26. Crea una matriz cuadrada de números reales y resta a cada fila la media de la fila.

#### 27. Dado un vector, ¿suma 1 a cada elemento de las posiciones indicadas en un segundo vector? (ten cuidado con los índices repetidos).
SUGERENCIA: Consulta la ayuda de la función `unique`.

#### 28. Considera el vector \[1, 2, 3, 4, 5\], construye un nuevo vector con 3 ceros consecutivos entre cada valor.

#### 29. Escribe un código que intercambie las dos filas de un array cuadrado de enteros pidiendo por teclado las dimensiones del array los números de fila a intercambiar

#### 30. Muestra los `n` valores mayores de un array de dimensión `m`, siendo `n` y `m` pedidos por teclado.