![Práctica 2 - Librería NUMPY](img/cabecera-Numpy.png)

# Ejercicios de Numpy

#### 1. Importa el paquete numpy con el nombre `np`.

In [2]:
import numpy as np

#### 2. Crea un vector de tamaño 10 lleno de ceros.

In [ ]:
np.zeros(10)

#### 3.  Crea un vector de ceros de tamaño 10 pero donde el quinto valor sea 1.

In [ ]:
n=np.zeros(10)
n[4]=1
print(n)

#### 4.  Crea un vector con todos los enteros del 10 al 49.

In [ ]:
np.arange(10,49,1)

#### 5.  Dale la vuelta a un vector (el primer elemento debe ser el último).

In [ ]:
print(n)
np.flip(n)

#### 6. Encuentra los índices de todos los valores distintos de cero el vector \[1,2,0,0,4,0\].

In [ ]:
m=np.array([1,2,0,0,4,0])
mask=(m!=0)
np.where(mask)

#### 7. Crea una matriz identidad de 3x3 (matriz de ceros con la diagonal principal a 1).

In [ ]:
np.eye(3)

#### 9. Crea un array de 3x3x3 de valores aleatorios.

In [ ]:
np.random.rand(3,3,3)

#### 10. Crea una matriz de 10x10 con números aleatorios y encuentra el mínimo y el máximo.

In [ ]:
n=np.random.rand(10,10)
min=np.min(n)
max=np.max(n)
print("Valor mínimo: ", min)
print("Valor máximo: ", max)

#### 11. Crea un vector aleatorio de tamaño 30 y calcula la media.

In [ ]:
n=np.random.rand(30)
mean=np.mean(n)
print("Media: ", mean)

#### 12. Crea un array de 2 dimensiones relleno de ceros y con el valor 1 en los bordes.

In [ ]:
n=np.zeros((10,10))
n[0,:]=1
n[:,0]=1
n[-1,:]=1
n[:,-1]=1
print(n)



#### 13. Crea una matriz de 8x8 rellena con un patrón de tablero de ajedrez (utiliza 0 y 1).

In [ ]:
n = np.zeros((8,8))
n[1::2, ::2] = 1
n[::2, 1::2] = 1
print(n)

#### 14. Normaliza una matriz aleatoria de 5x5 para que sus valores estén entre 0 y 1 (ambos deben estar incluidos).

In [ ]:
np.random.rand(5,5)
min=np.min(n)
max=np.max(n)
n=(n-min)/(max-min)
print(n)

#### 15. Multiplica una matriz de 5x3 por una de 3x2.

In [3]:
m1 = np.random.random((5,3))
m2 = np.random.random((3,2))
print(np.dot(m1, m2))

[[0.5391535  0.85629691]
 [0.30392335 0.51442539]
 [0.76869428 0.55235914]
 [0.36890752 0.4320472 ]
 [0.33883741 0.51084042]]


#### 16. Dado un array de 1 dimensión, cambia el signo de los elementos cuyo valor esté entre 3 y 8.

In [4]:
Z = np.arange(11)
mask = (Z >= 3) & (Z <= 8)
Z[mask] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 17. Encontrar los valores comunes en dos arrays.
SUGERENCIA: En Numpy hay funciones para manipular los arrays como conjuntos (intersección, unión, diferencia, ...)

In [5]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(A, B))

[3 4 5]


#### 18. ¿Es la siguiente expresión cierta?

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [7]:

print(np.sqrt(-1) == np.emath.sqrt(-1)) 

False


C:\Users\benro\AppData\Local\Temp\ipykernel_12304\915990631.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 19. Encuentra 3 formas diferentes de extraer la parte entera de los valores de un array de números reales aleatorios.

In [8]:
Z = np.random.uniform(0, 10, 5)
print(Z)
# Forma 1
print(np.floor(Z))
# Forma 2
print(Z.astype(int))
# Forma 3
print(np.trunc(Z))

[3.37302272 6.51906762 9.12360193 4.62292128 2.74762978]
[3. 6. 9. 4. 2.]
[3 6 9 4 2]
[3. 6. 9. 4. 2.]


#### 20. Crea una matriz de 5x5 en la que todas las filas contengan el rango de 0 a 4.

In [9]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 21. Crea un vector con 10 valores desde el 0 hasta el 1, pero sin incluir ni el 0, ni el 1.

In [10]:
Z = np.linspace(0, 1, 12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 22. Crea un vector aleatorio de tamaño 10 y ordénalo.

In [11]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06792337 0.09904513 0.28453433 0.39477154 0.46773138 0.49732758
 0.69029229 0.91856023 0.93791252 0.98962791]


#### 23. Considera dos arrays de enteros aleatorios A y B de tamaño 3. Muéstralos y comprueba si son iguales.

In [12]:
A = np.random.randint(0, 2, 3)
B = np.random.randint(0, 2, 3)
print("A:", A, "B:", B)
print("¿Son iguales?:", np.array_equal(A, B))

A: [1 1 0] B: [0 1 0]
¿Son iguales?: False


#### 24. Crea un array aleatorio de tamaño 10 y cambia el máximo valor por 0.

In [13]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.11816248 0.89967689 0.57326347 0.75033117 0.         0.89741299
 0.49300164 0.66022183 0.75777491 0.02323299]


#### 25. Encontrar en un array de números reales el valor mas cercano a un número dado que el programa debe pedir por teclado.

In [14]:
Z = np.random.uniform(0, 100, 10)
print("Array:", Z)
num = float(input("Introduce un número: "))
index = (np.abs(Z - num)).argmin()
print("Valor más cercano:", Z[index])

Array: [56.95028239 37.53863772 37.02986016 24.78490761 43.00422763 10.63124571
 54.45172415 34.78106603 10.96960996  4.17625343]
Valor más cercano: 4.176253429597887


#### 26. Crea una matriz cuadrada de números reales y resta a cada fila la media de la fila.

In [ ]:
X = np.random.rand(4, 4)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.32108232 -0.27862946  0.2023233  -0.24477616]
 [ 0.00064727  0.23872672 -0.25101119  0.0116372 ]
 [-0.37093984  0.34616022 -0.19870284  0.22348247]
 [-0.05632747 -0.07132119  0.08267893  0.04496972]]


#### 27. Dado un vector, ¿suma 1 a cada elemento de las posiciones indicadas en un segundo vector? (ten cuidado con los índices repetidos).
SUGERENCIA: Consulta la ayuda de la función `unique`.

In [16]:
Z = np.ones(10)
I = np.array([1, 2, 3, 3, 3])
np.add.at(Z, I, 1)
print(Z)

[1. 2. 2. 4. 1. 1. 1. 1. 1. 1.]


#### 28. Considera el vector \[1, 2, 3, 4, 5\], construye un nuevo vector con 3 ceros consecutivos entre cada valor.

In [17]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 29. Escribe un código que intercambie las dos filas de un array cuadrado de enteros pidiendo por teclado las dimensiones del array los números de fila a intercambiar

In [18]:
dim = int(input("Dimensión de la matriz: "))
M = np.arange(dim*dim).reshape(dim, dim)
print("Original:\n", M)
f1 = int(input("Fila 1 a intercambiar: "))
f2 = int(input("Fila 2 a intercambiar: "))
M[[f1, f2]] = M[[f2, f1]]
print("Resultado:\n", M)

Original:
 [[0]]


IndexError: index 1 is out of bounds for axis 0 with size 1

#### 30. Muestra los `n` valores mayores de un array de dimensión `m`, siendo `n` y `m` pedidos por teclado.

In [19]:
m = int(input("Tamaño del array (m): "))
n = int(input("Número de valores mayores (n): "))
Z = np.random.permutation(np.arange(m))
print("Array:", Z)
print("Los", n, "mayores:", Z[np.argsort(Z)[-n:]])

Array: [1 0]
Los 1 mayores: [1]
