![Práctica 2 - Librería NUMPY](img/cabecera-Numpy.png)

### REALIZADA POR: Adrián Benítez Roldán y Alejandro Montes Cantero

# Ejercicios de Numpy

#### 1. Importa el paquete numpy con el nombre `np`.

In [1]:
import numpy as np

#### 2. Crea un vector de tamaño 10 lleno de ceros.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Crea un vector de ceros de tamaño 10 pero donde el quinto valor sea 1.

In [3]:
n=np.zeros(10)
n[4]=1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Crea un vector con todos los enteros del 10 al 49.

In [4]:
np.arange(10,49,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5.  Dale la vuelta a un vector (el primer elemento debe ser el último).

In [5]:
print(n)
np.flip(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 6. Encuentra los índices de todos los valores distintos de cero el vector \[1,2,0,0,4,0\].

In [6]:
m=np.array([1,2,0,0,4,0])
mask=(m!=0)
np.where(mask)

(array([0, 1, 4]),)

#### 7. Crea una matriz identidad de 3x3 (matriz de ceros con la diagonal principal a 1).

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Crea un array de 3x3x3 de valores aleatorios.

In [8]:
np.random.rand(3,3,3)

array([[[0.40962169, 0.60772243, 0.92843428],
        [0.76192115, 0.82519257, 0.18757388],
        [0.23451671, 0.61884723, 0.36884478]],

       [[0.29929532, 0.57612525, 0.77106245],
        [0.40029078, 0.61341873, 0.87656437],
        [0.92441326, 0.6763003 , 0.71029411]],

       [[0.74531366, 0.87749276, 0.48083145],
        [0.79921068, 0.20074597, 0.75206538],
        [0.64949034, 0.98328211, 0.52967129]]])

#### 10. Crea una matriz de 10x10 con números aleatorios y encuentra el mínimo y el máximo.

In [9]:
n=np.random.rand(10,10)
min=np.min(n)
max=np.max(n)
print("Valor mínimo: ", min)
print("Valor máximo: ", max)

Valor mínimo:  0.002929287244396228
Valor máximo:  0.9978856763826519


#### 11. Crea un vector aleatorio de tamaño 30 y calcula la media.

In [10]:
n=np.random.rand(30)
mean=np.mean(n)
print("Media: ", mean)

Media:  0.5076476307592599


#### 12. Crea un array de 2 dimensiones relleno de ceros y con el valor 1 en los bordes.

In [11]:
n=np.zeros((10,10))
n[0,:]=1
n[:,0]=1
n[-1,:]=1
n[:,-1]=1
print(n)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 13. Crea una matriz de 8x8 rellena con un patrón de tablero de ajedrez (utiliza 0 y 1).

In [12]:
n = np.zeros((8,8))
n[1::2, ::2] = 1
n[::2, 1::2] = 1
print(n)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 14. Normaliza una matriz aleatoria de 5x5 para que sus valores estén entre 0 y 1 (ambos deben estar incluidos).

In [13]:
np.random.rand(5,5)
min=np.min(n)
max=np.max(n)
n=(n-min)/(max-min)
print(n)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 15. Multiplica una matriz de 5x3 por una de 3x2.

In [14]:
m1 = np.random.random((5,3))
m2 = np.random.random((3,2))
print(np.dot(m1, m2))

[[1.19423886 0.78714561]
 [0.76203577 0.73780837]
 [1.01618628 0.63373643]
 [0.09186932 0.35601665]
 [0.7475914  0.27467547]]


#### 16. Dado un array de 1 dimensión, cambia el signo de los elementos cuyo valor esté entre 3 y 8.

In [15]:
Z = np.arange(11)
mask = (Z >= 3) & (Z <= 8)
Z[mask] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 17. Encontrar los valores comunes en dos arrays.
SUGERENCIA: En Numpy hay funciones para manipular los arrays como conjuntos (intersección, unión, diferencia, ...)

In [16]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])
print(np.intersect1d(A, B))

[3 4 5]


#### 18. ¿Es la siguiente expresión cierta?

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [17]:

print(np.sqrt(-1) == np.emath.sqrt(-1)) 

False


C:\Users\aleja\AppData\Local\Temp\ipykernel_19100\915990631.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 19. Encuentra 3 formas diferentes de extraer la parte entera de los valores de un array de números reales aleatorios.

In [18]:
Z = np.random.uniform(0, 10, 5)
print(Z)
# Forma 1
print(np.floor(Z))
# Forma 2
print(Z.astype(int))
# Forma 3
print(np.trunc(Z))

[3.25405464 3.78271359 4.23500176 4.33072447 8.38328858]
[3. 3. 4. 4. 8.]
[3 3 4 4 8]
[3. 3. 4. 4. 8.]


#### 20. Crea una matriz de 5x5 en la que todas las filas contengan el rango de 0 a 4.

In [19]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 21. Crea un vector con 10 valores desde el 0 hasta el 1, pero sin incluir ni el 0, ni el 1.

In [20]:
Z = np.linspace(0, 1, 12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 22. Crea un vector aleatorio de tamaño 10 y ordénalo.

In [21]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00558754 0.15740606 0.18692947 0.21312219 0.2591632  0.41536369
 0.43163822 0.52697006 0.63858577 0.97154745]


#### 23. Considera dos arrays de enteros aleatorios A y B de tamaño 3. Muéstralos y comprueba si son iguales.

In [22]:
A = np.random.randint(0, 2, 3)
B = np.random.randint(0, 2, 3)
print("A:", A, "B:", B)
print("¿Son iguales?:", np.array_equal(A, B))

A: [1 1 0] B: [1 0 1]
¿Son iguales?: False


#### 24. Crea un array aleatorio de tamaño 10 y cambia el máximo valor por 0.

In [23]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.3367573  0.         0.24296082 0.13397564 0.7692377  0.09715796
 0.23679568 0.70943338 0.36205388 0.76627591]


#### 25. Encontrar en un array de números reales el valor mas cercano a un número dado que el programa debe pedir por teclado.

In [24]:
Z = np.random.uniform(0, 100, 10)
print("Array:", Z)
num = float(input("Introduce un número: "))
index = (np.abs(Z - num)).argmin()
print("Valor más cercano:", Z[index])

Array: [26.9931439  80.42502009 39.01836061 72.39941729 76.79350548 67.7774951
 66.04282102 30.57964476 89.43692863 73.47486974]
Valor más cercano: 39.018360611854355


#### 26. Crea una matriz cuadrada de números reales y resta a cada fila la media de la fila.

In [25]:
X = np.random.rand(4, 4)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.33613011  0.16854052 -0.2420546   0.40964418]
 [-0.13800788  0.0160595  -0.01463661  0.13658499]
 [-0.26320256  0.27042087  0.22974619 -0.23696451]
 [ 0.23807636  0.04850048 -0.18250182 -0.10407501]]


#### 27. Dado un vector, ¿suma 1 a cada elemento de las posiciones indicadas en un segundo vector? (ten cuidado con los índices repetidos).
SUGERENCIA: Consulta la ayuda de la función `unique`.

In [26]:
Z = np.ones(10)
I = np.array([1, 2, 3, 3, 3])
np.add.at(Z, I, 1)
print(Z)

[1. 2. 2. 4. 1. 1. 1. 1. 1. 1.]


#### 28. Considera el vector \[1, 2, 3, 4, 5\], construye un nuevo vector con 3 ceros consecutivos entre cada valor.

In [27]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 29. Escribe un código que intercambie las dos filas de un array cuadrado de enteros pidiendo por teclado las dimensiones del array los números de fila a intercambiar

In [28]:
dim = int(input("Dimensión de la matriz: "))
M = np.arange(dim*dim).reshape(dim, dim)
print("Original:\n", M)
f1 = int(input("Fila 1 a intercambiar: "))
f2 = int(input("Fila 2 a intercambiar: "))
M[[f1, f2]] = M[[f2, f1]]
print("Resultado:\n", M)

Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Resultado:
 [[ 0  1  2  3]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]]


#### 30. Muestra los `n` valores mayores de un array de dimensión `m`, siendo `n` y `m` pedidos por teclado.

In [29]:
m = int(input("Tamaño del array (m): "))
n = int(input("Número de valores mayores (n): "))
Z = np.random.permutation(np.arange(m))
print("Array:", Z)
print("Los", n, "mayores:", Z[np.argsort(Z)[-n:]])

Array: [1 2 5 6 7 4 8 3 9 0]
Los 5 mayores: [5 6 7 8 9]
